server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacare
    username: pharmacare
    password: pharmacare
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
    expirationMinutes: 120
  files:
    prescriptionsDir: "./data/prescriptions"
